In [1]:
import pandas  as pd

In [2]:
df = pd.read_csv("weight-height.csv")
df.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
df = df.drop(["Gender"], axis=1)
df.head()

      Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [4]:
df.isna().sum()

Height    0
Weight    0
dtype: int64